### ISSUE TITLE
Create glossary

### ISSUE THREAD

**Issue by jackVanish** [ocean-tracking-network/jb-acoustic-telemetry#4]
Vanilla Carpentries lessons have glossaries that they link to from the lessons (http://swcarpentry.github.io/python-novice-inflammation/reference/#variable). It contains the key points as well as various definitions of technical terms. We may want to think about making one of these for ourselves in this. Maybe keep track of some terms that we should glossarize in this ticket?

**Comment by jackVanish** [comment]
I've been through the text and here's what I think we need to define in the glossary, in no particular order. I'll alphabetize them later. 

- dplyr
- glatos
- stringr
- Acoustic telemetry
- Lubridate
- Time series
- R
- station
- ping
- data cleaning
- abacus plot
- FishID
- tagging date
- fork length
- MapBox
- posix
- tx receivers
- residence index
- COA/Centers of Activity
- Brownian bridges
- ATT

It's possible and indeed likely that some of these will already be familiar to the intended audience; however, nobody's forced to look at the glossary and I think more is generally better when it comes to clarification of terms. If we're already making the glossary, it's not that much extra effort to have more terms. 

@jdpye Marshal some appropriate definitions and when you have them, I'll make a page out of it.

**Comment by jdpye** [comment]
Super-fast definitions for these terms. People should edit and refine these, especially the statistical ones...:

**dplyr**: A data manipulation library focused on manipulating, subsetting, summarizing data frames (square matrices of data). Very useful for working with our tabular datasets. Part of the 'Tidyverse' family of R packages.
**glatos**: a package maintained by the telemetry network of the same name to ingest, standardize, and operate on acoustic telemetry datasets.
**stringr**: Character string manipulator library. Part of the 'Tidyverse' family of R packages.
**Acoustic telemetry**: The practice of affixing animals with uniquely-coded acoustic pingers and deploying listening stations to identify and locate them over time.
**Lubridate**: Date manipulator package. Part of the 'Tidyverse' family of R packages.
**Time series**: A dataset that takes measurements regularly over a period of time.
**R**: A statistical programming language.
station: A geographical location where listening equipment is deployed and recovered regularly.
**ping**: A series of transmissions made by an acoustic tag for the purposes of relaying its unique code to a listening instrument.
**data cleaning**: The process of removing irregularities in formatting, errors, and typos from data to ensure uniform operation in analysis and visualization
**abacus plot**: A dot-plot, often with time as the X axis, station as the Y axis, and individual ID as the color-code, popular in telemetry studies to show patterns of animal spatial use over time.
**FishID**: A unique identifier for an individual animal observed at a location and time, regardless of the method of location. Often synonymous with `catalognumber` and `animalID`
**tagging date**: The date an animal was affixed with an electronic tag (acoustic or otherwise).
**fork length**: A common measurement for fish length, the length from nose to tail fork.
**MapBox**: A geospatial visualization library, an open source mapping platform for custom-designed maps.
**POSIX**: A set of IEEE standards that are meant to guarantee interoperability. In most common R parlance, it's a shorthand for the functions that standardize the format for a date and time 
**Tx receivers**: Listening devices that also transmit their own coded pings, for the purposes of synchronizing clocks or for being heard by mobile listening stations.
**residence index**: Any of a few ratios that can be calculated to determine the relative spatial use of an animal across an observatory of listening devices.
**COA/Centers of Activity**: An estimate of relative spatial activity given input data about animal positions in time. Based on technique described in: Simpfendorfer, C. A., M. R. Heupel, and R. E. Hueter. 2002. Estimation of short-term centers of activity from an array of omnidirectional hydrophones and its use in studying animal movements. Canadian Journal of Fisheries and Aquatic Sciences 59:23-32.
**Brownian bridges**: a conditional probability distribution that pins the process at both origin and a second time (t), a paradigm that is very useful for estimating path probability between two known events (i.e.: the location of an animal at two points in time and space)
**ATT**: A set of metadata formats implemented as an object in R. Devised by Vinay Udyawer of AIMS for use in the VTrack analysis package, standardizing the reporting of listening device deployment and recovery, tagging efforts, and detection events into one uniform data format.
